export interface Find {
    title?: RegExp,
    description?: string,
    employerId?: string,
    job_categorie_id?: string,
    website?: string,
    level?: string,
    jobType?: string,
    salaryMin?: number,
    salaryMax?: any,
    ageMin?: number,
    ageMax?: number,
    gender?: string,
    educationalLevel?: string,
    workExperience?: string,
    presentationLanguage?: string,
    status?: string,
    detailWorkExperience?: string,
    linkVideoAboutIntroducingJob?: string,
    welfare?: string,
    listTagSlug?: string[],
    phone?: string,
    email?: string,
    featured?: boolean,
    end_date?: any,
    listTagName?: string[],
    receiveEmail?: boolean,
    address?: {
      location: string,
      linkMap: string,
    },
    keyword?: RegExp,
    deleted?: boolean,
    city?: string[],
    $or?: any,
    slug?: string,
  }